[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]

#  pytest fixture fix
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["F811", "F401"]
